-
--
-- Table structure for table `GTS_TIMEZONES`
--

CREATE TABLE `GTS_TIMEZONES`(
  `GTS_TIMEZONE_ID`           INTEGER     NOT NULL     PRIMARY KEY  ,
  `GTS_TIMEZONE_NAME`         VARCHAR(50)  NOT NULL    UNIQUE,
  `GTS_TIMEZONE_DESCRIPTION`  VARCHAR(100) ,
  `GTS_TIMEZONE_STATUS`       BIT NOT NULL
  
) 